startDelaySecs: 5
ssl: false
blacklistObjectNames: ["java.lang:*"]
rules:
  - pattern: 'org.apache.activemq.artemis<broker=\"([^,]+)\"><>ConnectionCount'
    name: artemis_connection_count
    help: Number of clients connected to this Broker
    type: GAUGE
    labels:
      broker: $1
  - pattern: 'org.apache.activemq.artemis<broker=\"([^,]+)\", component=addresses, address=\"([^,]+)\"><>ConsumerCount'
    name: artemis_consumer_count
    type: GAUGE
    labels:
      broker: $1
      address: $2
